
const routes = [
    {
        path: '/',
        component: () => import('layouts/MonstockLayout.vue'),
        children: [
            { path: '', component: () => import('pages/Index.vue') },
            { path: '/publish/SoceRadarChart', component: () => import('components/ScoreRadarChart.vue') },
            { path: '/publish/BackDropDialog', component: () => import('components/BackDropDialog.vue') },
            { path: '/publish/FroalaEditor', component: () => import('components/FroalaEditor.vue') },
            { path: '/publish/A_10000_P', component: () => import('pages/publish/A_10000_P.vue') },
            { path: '/publish/A_11000_P', component: () => import('pages/publish/A_11000_P.vue') },
            { path: '/publish/A_11100_P', component: () => import('pages/publish/A_11100_P.vue') },
            { path: '/publish/A_11200_P', component: () => import('pages/publish/A_11200_P.vue') },
            { path: '/publish/A_12000_P', component: () => import('pages/publish/A_12000_P.vue') },
            { path: '/publish/A_12100_U', component: () => import('pages/publish/A_12100_U.vue') },
            { path: '/publish/A_12200_U', component: () => import('pages/publish/A_12200_U.vue') },
            { path: '/publish/A_21121_P', component: () => import('pages/publish/A_21121_P.vue') },
            { path: '/publish/A_21120_T', component: () => import('pages/publish/A_21120_T.vue') },
            { path: '/publish/A_21000_T', component: () => import('pages/publish/A_21000_T.vue') },
            { path: '/publish/A_22100_P', component: () => import('pages/publish/A_22100_P.vue') },
            { path: '/publish/A_21310_T', component: () => import('pages/publish/A_21310_T.vue') },
            { path: '/publish/A_21510_T', component: () => import('pages/publish/A_21510_T.vue') },
            { path: '/publish/A_21530_T', component: () => import('pages/publish/A_21530_T.vue') },
            { path: '/publish/A_70000_P', component: () => import('pages/publish/A_70000_P.vue') },
            { path: '/publish/A_22923_P', component: () => import('pages/publish/A_22923_P.vue') },
            { path: '/publish/A_100_U', component: () => import('pages/publish/A_100_U.vue') },
            { path: '/publish/A_101_U', component: () => import('pages/publish/A_101_U.vue') },
            { path: '/publish/A_102_U', component: () => import('pages/publish/A_102_U.vue') },
            { path: '/publish/A_103_U', component: () => import('pages/publish/A_103_U.vue') },
            { path: '/publish/A_104_U', component: () => import('pages/publish/A_104_U.vue') },
            { path: '/publish/A_105_U', component: () => import('pages/publish/A_105_U.vue') },
            { path: '/publish/A_106_U', component: () => import('pages/publish/A_106_U.vue') },
            { path: '/publish/A_50000_P', component: () => import('pages/publish/A_50000_P.vue') },
            { path: '/publish/H_21000_T', component: () => import('pages/publish/H_21000_T.vue') },
            { path: '/publish/A_51100_P', component: () => import('pages/publish/A_51100_P.vue') },
            { path: '/publish/C_21100_T', component: () => import('pages/publish/C_21100_T.vue') },
            { path: '/publish/H_50000_P', component: () => import('pages/publish/H_50000_P.vue') },
            { path: '/publish/H_41000_T', component: () => import('pages/publish/H_41000_T.vue') },
            { path: '/publish/A_51310_P', component: () => import('pages/publish/A_51310_P.vue') },
            { path: '/publish/A_513111_P', component: () => import('pages/publish/A_513111_P.vue') },
            { path: '/publish/A_51311_P', component: () => import('pages/publish/A_51311_P.vue') },
            { path: '/publish/C_10000_P', component: () => import('pages/publish/C_10000_P.vue') },
            { path: '/publish/A_500_P', component: () => import('pages/publish/A_500_P.vue') },
            { path: '/publish/A_501_P', component: () => import('pages/publish/A_501_P.vue') },
            { path: '/publish/A_502_P', component: () => import('pages/publish/A_502_P.vue') },
            { path: '/publish/A_503_P', component: () => import('pages/publish/A_503_P.vue') },
            { path: '/publish/A_504_P', component: () => import('pages/publish/A_504_P.vue') },
            { path: '/publish/A_505_P', component: () => import('pages/publish/A_505_P.vue') },
            { path: '/publish/A_506_P', component: () => import('pages/publish/A_506_P.vue') },
            { path: '/publish/A_507_P', component: () => import('pages/publish/A_507_P.vue') },
            { path: '/publish/C_20000_T', component: () => import('pages/publish/C_20000_T.vue') },
            { path: '/publish/C_41000_T', component: () => import('pages/publish/C_41000_T.vue') },
            { path: '/publish/H_10000_P', component: () => import('pages/publish/H_10000_P.vue') },
            { path: '/publish/H_11115_U', component: () => import('pages/publish/H_11115_U.vue') },
            { path: '/publish/H_11220_U', component: () => import('pages/publish/H_11220_U.vue') },
            { path: '/publish/H_11210_P', component: () => import('pages/publish/H_11210_P.vue') },
            { path: '/publish/H_11111_P', component: () => import('pages/publish/H_11111_P.vue') },
            { path: '/publish/H_20000_P', component: () => import('pages/publish/H_20000_P.vue') },
            { path: '/publish/H_11112_U', component: () => import('pages/publish/H_11112_U.vue') },
            { path: '/publish/H_11113_U', component: () => import('pages/publish/H_11113_U.vue') },
            { path: '/publish/H_11114_U', component: () => import('pages/publish/H_11114_U.vue') },
            { path: '/publish/H_300_P', component: () => import('pages/publish/H_300_P.vue') },
            { path: '/publish/H_31000_T', component: () => import('pages/publish/H_31000_T.vue') },
            { path: '/publish/H_35000_T', component: () => import('pages/publish/H_35000_T.vue') },
            { path: '/publish/H_32000_T', component: () => import('pages/publish/H_32000_T.vue') },
            { path: '/publish/H_33100_T', component: () => import('pages/publish/H_33100_T.vue') },
            { path: '/publish/H_33200_T', component: () => import('pages/publish/H_33200_T.vue') },
            { path: '/publish/H_33300_T', component: () => import('pages/publish/H_33300_T.vue') },
            { path: '/publish/H_31210_P', component: () => import('pages/publish/H_31210_P.vue') },
            { path: '/publish/H_31310_P', component: () => import('pages/publish/H_31310_P.vue') },
            { path: '/publish/H_31320_P', component: () => import('pages/publish/H_31320_P.vue') },
            { path: '/publish/H_31321_P', component: () => import('pages/publish/H_31321_P.vue') },
            { path: '/publish/H_31322_P', component: () => import('pages/publish/H_31322_P.vue') },
            { path: '/publish/H_31323_P', component: () => import('pages/publish/H_31323_P.vue') },
            { path: '/publish/H_32110_P', component: () => import('pages/publish/H_32110_P.vue') },
            { path: '/publish/votinglist', component: () => import('pages/publish/votinglist.vue') },
            { path: '/publish/H_301_P', component: () => import('pages/publish/H_301_P.vue') },
            { path: '/publish/A_21711_T', component: () => import('pages/publish/A_21711_T.vue') },
            { path: '/publish/A_217121_U', component: () => import('pages/publish/A_217121_U.vue') },
            { path: '/publish/H_11110_P', component: () => import('pages/publish/H_11110_P.vue') },
            { path: '/publish/H_11911_T', component: () => import('pages/publish/H_11911_T.vue') },
            { path: '/publish/H_10000_P2', component: () => import('pages/publish/H_10000_P2.vue') },
            { path: '/publish/A_217122_U', component: () => import('pages/publish/A_217122_U.vue') },
            { path: '/publish/A_217221_U', component: () => import('pages/publish/A_217221_U.vue') },
            { path: '/publish/A_217222_U', component: () => import('pages/publish/A_217222_U.vue') },
            { path: '/publish/A_217311_U', component: () => import('pages/publish/A_217311_U.vue') },
            { path: '/publish/A_217312_U', component: () => import('pages/publish/A_217312_U.vue') },
            { path: '/publish/A_217321_U', component: () => import('pages/publish/A_217321_U.vue') },
            { path: '/publish/A_217322_U', component: () => import('pages/publish/A_217322_U.vue') },
            { path: '/publish/A_51211_T', component: () => import('pages/publish/A_51211_T.vue') },
            { path: '/publish/A_51221_T', component: () => import('pages/publish/A_51221_T.vue') },
            { path: '/publish/A_30000_P', component: () => import('pages/publish/A_30000_P.vue') },
            { path: '/publish/A_31000_P', component: () => import('pages/publish/A_31000_P.vue') },
            { path: '/publish/A_61000_P', component: () => import('pages/publish/A_61000_P.vue') },
            { path: '/publish/A_61100_P', component: () => import('pages/publish/A_61100_P.vue') },
            { path: '/publish/A_62000_P', component: () => import('pages/publish/A_62000_P.vue') },
            { path: '/publish/A_63000_P', component: () => import('pages/publish/A_63000_P.vue') },
            { path: '/publish/A_63100_P', component: () => import('pages/publish/A_63100_P.vue') },
            { path: '/publish/A_63200_P', component: () => import('pages/publish/A_63200_P.vue') },
            { path: '/publish/A_63300_P', component: () => import('pages/publish/A_63300_P.vue') },
            { path: '/publish/A_41000_P', component: () => import('pages/publish/A_41000_P.vue') },
            { path: '/publish/A_41100_P', component: () => import('pages/publish/A_41100_P.vue') },
            { path: '/publish/A_601_P', component: () => import('pages/publish/A_601_P.vue') },
            { path: '/publish/A_602_P', component: () => import('pages/publish/A_602_P.vue') },
            { path: '/publish/A_603_P', component: () => import('pages/publish/A_603_P.vue') },
            { path: '/publish/A_604_P', component: () => import('pages/publish/A_604_P.vue') },
            { path: '/publish/H_12000_T', component: () => import('pages/publish/H_12000_T.vue') },
            { path: '/publish/H_12310_T', component: () => import('pages/publish/H_12310_T.vue') },
            { path: '/publish/H_12710_T', component: () => import('pages/publish/H_12710_T.vue') },
            { path: '/publish/H_12e10_T', component: () => import('pages/publish/H_12e10_T.vue') },
            { path: '/publish/H_12810_T', component: () => import('pages/publish/H_12810_T.vue') },
            { path: '/publish/H_12c10_T', component: () => import('pages/publish/H_12c10_T.vue') },
            { path: '/publish/H_12d10_T', component: () => import('pages/publish/H_12d10_T.vue') },
            
        ]
    },
    {
        path: '/publish',
        component: () => import('layouts/MonstockLayout1.vue'),
        children: [
            { path: '', component: () => import('src/pages/publish/index.vue') },
            { path: '/UiGuide', component: () => import('pages/publish/UiGuide.vue') }
        ]
    },    
    // Always leave this as last one,
    // but you can also remove it
    {
        path: '*',
        component: () => import('pages/Error404.vue')
    }
];

export default routes;
